# Generated by Django 4.2.7 on 2024-04-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('min_salary', models.PositiveIntegerField(default=10)),
                ('max_salary', models.PositiveIntegerField()),
                ('salary_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('hourly', 'Hourly')], max_length=10)),
                ('job_location', models.CharField(max_length=50)),
                ('job_posting_date', models.DateField(auto_now=True)),
                ('experience', models.CharField(choices=[('internship', 'Internship'), ('freshers', 'Freshers'), ('experienced', 'Experienced')], max_length=50)),
                ('required_skill', models.JSONField()),
                ('company_logo', models.URLField(null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='static/resumes')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
