# Generated by Django 5.0 on 2024-01-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
