# Generated by Django 5.0 on 2024-01-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_max_salary_alter_job_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50),
        ),
    ]
